import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, JetBrains_Mono, Russo_One } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getTranslations } from "next-intl/server";
import { ThemeProvider } from "next-themes";
import { LocaleSwitcher } from "@/components/locale-switcher";
import { ThemeSwitcher } from "@/components/theme-switcher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Texte à taper : lisible, accents français compris.
const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

// Titres : style arcade sportif.
const russoOne = Russo_One({
  variable: "--font-russo-one",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const t = await getTranslations("Footer");

  return (
    <html
      lang={await getLocale()}
      className={`${geistSans.variable} ${jetBrainsMono.variable} ${russoOne.variable} h-full antialiased`}
      // next-themes ajoute la classe du thème avant l'hydratation.
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <NextIntlClientProvider>
            <header className="flex items-center gap-6 p-4">
              {/* Voiture bleue et boost blanc en sombre, voiture orange et boost noir en clair. */}
              <Link href="/" className="mr-auto">
                <Image src="/logo-light.svg" alt="Taype-in" width={129} height={56} className="dark:hidden" />
                <Image src="/logo-dark.svg" alt="Taype-in" width={129} height={56} className="hidden dark:block" />
              </Link>
              <ThemeSwitcher />
              <LocaleSwitcher />
            </header>
            {children}
            <footer className="mt-auto p-4 text-center text-sm text-muted">{t("disclaimer")}</footer>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
